service: serverless


provider:

  name: aws

  runtime: nodejs12.x

  stage: mine

  region: ap-south-1


functions:

  app:

    handler: index.handler

    events:

      - http: ANY /

      - http: 'ANY {proxy+}'