service: sls-crud-complete


provider:

  name: aws

  runtime: nodejs12.x

  stage: sls-complete

  region: ap-south-1


functions:

  app:

    handler: index.handler

    events:

      - http: GET /

      - http: POST /
      - http: PUT /
      - http: DELETE /


